name = "Unfold"
uuid = "181c99d8-e21b-4ff3-b70b-c233eddec679"
authors = ["Benedikt Ehinger <science@benediktehinger.de>"]
version = "0.6.6"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Effects = "8f03c58b-bd97-4933-a826-f71b64d2cca2"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RobustModels = "d6ea1423-9682-4bbd-952f-b1577cbf8c98"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
RobustModels = "d6ea1423-9682-4bbd-952f-b1577cbf8c98"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"

[extensions]
UnfoldBSplineKitExt = "BSplineKit"
UnfoldMixedModelsExt = "MixedModels"
UnfoldRobustModelsExt = "RobustModels"
UnfoldKrylovExt = ["Krylov","CUDA"]

[compat]
BSplineKit = "0.16,0.17"
CUDA = "4,5"
DSP = "0.7"
DataFrames = "1"
Distributions = "0.25"
DocStringExtensions = "0.9"
Effects = "0.1,1"
FileIO = "1"
GLM = "1"
IterativeSolvers = "0.9"
JLD2 = "0.4"
Krylov = "0.9"
MLBase = "0.9"
Missings = "1"
MixedModels = "4"
ProgressMeter = "1"
RobustModels = "0.4,0.5"
StaticArrays = "1"
StatsBase = "0.33,0.34"
StatsFuns = "1"
StatsModels = "0.6,0.7"
Tables = "1"
TimerOutputs = "0.5"
julia = "1.6"
