[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"
